export type ApiFieldErrors = Record<string, string[] | undefined>;

export type ApiErrorCode =
  | "INVALID_CONTENT_TYPE"
  | "PAYLOAD_TOO_LARGE"
  | "INVALID_JSON"
  | "VALIDATION_ERROR"
  | "UNAUTHENTICATED"
  | "FORBIDDEN"
  | "CROSS_SITE_REQUEST_BLOCKED"
  | "EMAIL_ALREADY_EXISTS"
  | "REGISTRATION_FAILED"
  | "MEMBER_NOT_FOUND"
  | "MEMBER_UPDATE_FAILED"
  | "SELF_MANAGEMENT_FORBIDDEN"
  | "LAST_ADMIN_REQUIRED"
  | "INVITATION_NOT_FOUND"
  | "INVITATION_EXPIRED"
  | "INVITATION_REVOKED"
  | "INVITATION_ALREADY_ACCEPTED"
  | "INVITATION_EMAIL_UNAVAILABLE"
  | "INVITATION_CREATE_FAILED"
  | "INVITATION_REVOKE_FAILED"
  | "INVITATION_ACCEPT_FAILED"
  | "FEEDBACK_NOT_FOUND"
  | "FEEDBACK_SOURCE_REF_CONFLICT"
  | "FEEDBACK_STATUS_TRANSITION_INVALID"
  | "FEEDBACK_STATUS_TRANSITION_CONFLICT"
  | "FEEDBACK_LIST_FAILED"
  | "FEEDBACK_CREATE_FAILED"
  | "FEEDBACK_UPDATE_FAILED"
  | "FEEDBACK_CLASSIFICATION_IN_PROGRESS"
  | "FEEDBACK_CLASSIFICATION_FAILED"
  | "CSV_FILE_REQUIRED"
  | "CSV_FILE_INVALID"
  | "CSV_FILE_TOO_LARGE"
  | "CSV_EMPTY"
  | "CSV_PARSE_FAILED"
  | "CSV_HEADER_INVALID"
  | "CSV_ROW_LIMIT_EXCEEDED"
  | "CSV_IMPORT_FAILED"
  | "SIMULATED_CHANNEL_IMPORT_FAILED"
  | "DASHBOARD_ANALYTICS_FAILED"
  | "INTERNAL_SERVER_ERROR";

export type ApiErrorResponse = {
  success: false;
  error: {
    code: ApiErrorCode;
    message: string;
    fieldErrors?: ApiFieldErrors;
  };
};

export type ApiSuccessResponse<TData> = {
  success: true;
  data: TData;
};